DROP TABLE IF EXISTS PROJECTS CASCADE;
CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;
CREATE TABLE IF NOT EXISTS PROJECTS
(
    ID                      SERIAL PRIMARY KEY,
    CREATED_TIMESTAMP              TIMESTAMP NOT NULL,
    MODIFIED_TIMESTAMP              TIMESTAMP   NOT NULL,
    TOTAL_TASKS                 INTEGER DEFAULT 0,
    COMPLETED_TASKS                 INTEGER DEFAULT 0,
    PROJECT_NAME                TEXT NOT NULL
);
SELECT create_hypertable('PROJECTS', 'CREATED_TIMESTAMP', if_not_exists => TRUE);
