DROP TABLE IF EXISTS TASKS CASCADE;
CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;
CREATE TABLE IF NOT EXISTS TASKS
(
    ID                      SERIAL,
    CREATED_TIMESTAMP       TIMESTAMP NOT NULL,
    STARTED_TIMESTAMP       TIMESTAMP   DEFAULT NULL,
    FINISHED_TIMESTAMP      TIMESTAMP DEFAULT NULL,
    PROGRESS                TEXT DEFAULT NULL,
    TASK_TYPE_NAME          TEXT NOT NULL,
    TASK_NAME               TEXT NOT NULL,
    TASK_DESCRIPTION        TEXT NOT NULL,
    PROJECT_ID              SERIAL,
    PRIMARY KEY (ID, TASK_NAME, CREATED_TIMESTAMP),
    CONSTRAINT FK_PROJECTS
          FOREIGN KEY(PROJECT_ID) 
	        REFERENCES PROJECTS(ID)
);
SELECT create_hypertable('TASKS', 'created_timestamp', if_not_exists => TRUE, create_default_indexes => FALSE);
