DROP TABLE IF EXISTS TASKS CASCADE;
CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;
CREATE TABLE IF NOT EXISTS TASKS
(
    ID                      SERIAL PRIMARY KEY,
    CREATED_TIMESTAMP       TIMESTAMP NOT NULL,
    STARTED_TIMESTAMP       TIMESTAMP   DEFAULT NULL,
    FINISHED_TIMESTAMP      TIMESTAMP DEFAULT NULL,
    PROGRESS                TEXT DEFAULT NULL,
    TASK_TYPE_NAME          TEXT NOT NULL,
    TASK_NAME               TEXT NOT NULL,
    PROJECT_ID              SERIAL,
    CONSTRAINT FK_PROJECTS
          FOREIGN KEY(PROJECT_ID) 
	        REFERENCES PROJECTS(ID)
);
SELECT create_hypertable('TASKS', 'CREATED_TIMESTAMP', if_not_exists => TRUE);
