DROP TABLE IF EXISTS TASKS CASCADE;
CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;
CREATE TABLE IF NOT EXISTS TASKS
(
    ID                      SERIAL,
    CREATED_TIMESTAMP       TIMESTAMP NOT NULL,
    STARTED_TIMESTAMP       TIMESTAMP   DEFAULT NULL,
    FINISHED_TIMESTAMP      TIMESTAMP DEFAULT NULL,
    STATUS                TEXT DEFAULT NULL,
    TASK_TYPE_NAME          TEXT NOT NULL,
    TASK_NAME               TEXT NOT NULL,
    TASK_DESCRIPTION        TEXT,
    PROJECT_NAME              TEXT,
    PRIMARY KEY (TASK_NAME, PROJECT_NAME, CREATED_TIMESTAMP),
    CONSTRAINT FK_PROJECTS
          FOREIGN KEY(PROJECT_NAME) 
	        REFERENCES PROJECTS(PROJECT_NAME)
);
SELECT create_hypertable('TASKS', 'created_timestamp', if_not_exists => TRUE, create_default_indexes => FALSE);
