productName: omnisearch
productVersion: 1.0.0 

nodeId: "product"

swagger: True
domainName: localhost
backendDomainName: localhost:6443
frontendDomainName: localhost:3000

datasource:
  migrate: true
  properties:
    - datasourceName: people-finder,project-mgt
      jdbcUrl: jdbc:postgresql://${POSTGRESQL_HOST_NAME}:5432/omnisearch?useSSL=false
      dataSource.user: iris
      dataSource.password: cymophane
      initializationFailTimeout: 0

