productName: omnisearch
productVersion: 1.0.0 

nodeId: "product"

swagger: True
domainName: localhost
backendDomainName: localhost:6443
frontendDomainName: localhost:3000

datasource:
  migrate: true
  properties:
    - datasourceName: people-finder
      jdbcUrl: jdbc:postgresql://${POSTGRESQL_HOST_NAME}:5432/ibis
      dataSource.user: coflex
      dataSource.password: coflex
      initializationFailTimeout: 0

