version: "2"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_realestate
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: realestate
      MYSQL_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - "./mysql/scripts:/docker-entrypoint-initdb.d"

  modules:
    restart: unless-stopped
    container_name: modules
    build:
      context: ./modules
      dockerfile: Dockerfile
    network_mode: host
    privileged: true
    cap_add:
      - NET_ADMIN
    volumes:
      - "./modules/conf:/usr/src/conf"
      - "./modules/logs:/usr/src/logs"
    environment:
        JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,address=0.0.0.0:8000,server=y,suspend=n"
volumes:
  mysql_data: {}
